### ISSUE TITLE
About documentation and examples

### ISSUE THREAD

**Issue by DuckZh** [Rooholla-KhorramBakht/Go2Py#6]
Awesome work! Would you provide some more documentation or other examples for us to explore? Since I am more familiar with python than C++, so I prefer to use this package for future development. Also, do you have a plan for simulation in gazebo or other simulation platforms?

**Comment by Rooholla-KhorramBakht** [comment]
Hi, thanks for the interest! We'll be adding more examples and Isaac-sim (Orbit) simulation support in the future. Regarding documentation, we will be adding some explanation to the provided notebook soon. But do you have any suggestions on any specific aspect you'd like to be documented better?

**Comment by DuckZh** [comment]
Thank you for reply. I'm especially curious to know how, as a beginner, I can use your library to develop and simulate some actions for  GO2. I've studied your provided examples and they are quite comprehensible, yet I haven't managed to put together a full functional workflow. I would greatly appreciate any guidance you could offer.
